# These are supported funding model platforms

github: lofcz
patreon: lofcz
open_collective: lofcz
ko_fi: lofcz
tidelift: lofcz
community_bridge: lofcz
liberapay: lofcz
issuehunt: lofcz
otechie: lofcz
custom: lofcz
